In [1]:
import numpy as np
import sys
if "../" not in sys.path:
    sys.path.append("../")
from lib.envs.gridworld import GridworldEnv

In [10]:
env = GridworldEnv()

Evaluate the policy given an environment and a full description of the environments dynamics.

Args:
    policy = [S,A] shaped matrix representing the policy
    env = OpenAI env. env.p represent the transition probilities of the environment.
    env.nS is the number of state in the environment.
    env.nA is the number of action in the environment.
    theta: we stop evaluation once our value function change is less than theta for all states.
    discount_factor = Gamma is a discount factor
    
Returns:
    vector of length env.nS representing the value function.

In [3]:
def policy_eval(policy, env, discount_factor=1.0, theta=0.00001):
    #start with a random (all theta) value
    V = np.zeros(env.nS)
    while True:
        #Todo implement!
        break
    return np.array(V)

In [7]:
random_policy = np.ones([env.nS, env.nA]) / env.nA
v = policy_eval(random_policy, env)
#print(v)
#print(random_policy)

In [8]:
#make sure evaluation policy is what we expected
expected_v = np.array([0, -14, -20, -22, -14, -18, -20, -20, -20, -20, -18, -14, -22, -20, -14, 0])
np.testing.assert_array_almost_equal(v, expected_v, decimal=2)

AssertionError: 
Arrays are not almost equal to 2 decimals

Mismatch: 87.5%
Max absolute difference: 22.
Max relative difference: nan
 x: array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
 y: array([  0, -14, -20, -22, -14, -18, -20, -20, -20, -20, -18, -14, -22,
       -20, -14,   0])

# Solution

In [33]:
from IPython.core.debugger import set_trace
import numpy as np
import pprint
import sys
if "../" not in sys.path:
    sys.path.append("../")
from lib.envs.gridworld import GridworldEnv

In [34]:
pp = pprint.PrettyPrinter(indent = 2)
env = GridworldEnv()

In [35]:
def policy_eval(policy, env, discount_factor = 1.0, theta = 0.00001):
    """Evaluate a policy given an environment 
    Args:
        Policy: [S, A] shaped matrix representing the policy.
        env = openAI env.  env.P represent the transition probabilities of the environment.
        env.P[s][a] is a list of transition tuples (prob, next_state, reward, done).
        env.nS is a number of state in the environment.
        env.nA is a number of action in the environment.
        theta: We stop our evaluation once our value function change is less than theta for all states.
        discount_factor = Gamma is our discount factor
        
        Return vector length env.nS representing value function"""
    #start with random (all theta) value
    V = np.zeros(env.nS)
    while True:
        delta = 0
        #for each step perform a "full back up"
        for s in range(env.nS):
            v = 0
            #look at the possible next action
            for a, action_prob in enumerate(policy[s]):
                #for each action look at the possible next step
                for prob, next_state, reward, done in env.P[s][a]:
                    #calculate the expected value
                    v += action_prob*prob*(reward + discount_factor*V[next_state])
                    #how much our value function changed across any state
                    
            delta = max(delta, np.abs(v - V[s]))
            V[s] = v
            
        #stop evaluating once our value function change is below a threshold
        if delta < theta:
            break
    return np.array(V)

In [36]:
random_policy = np.ones([env.nS, env.nA]) / env.nA
v = policy_eval(random_policy, env)

In [37]:
print("Value Function:")
print(v)
print("")
print("Reshaped grid value function: ")
print(v.reshape(env.shape))
print("")

Value Function:
[  0.         -13.99993529 -19.99990698 -21.99989761 -13.99993529
 -17.9999206  -19.99991379 -19.99991477 -19.99990698 -19.99991379
 -17.99992725 -13.99994569 -21.99989761 -19.99991477 -13.99994569
   0.        ]

Reshaped grid value function: 
[[  0.         -13.99993529 -19.99990698 -21.99989761]
 [-13.99993529 -17.9999206  -19.99991379 -19.99991477]
 [-19.99990698 -19.99991379 -17.99992725 -13.99994569]
 [-21.99989761 -19.99991477 -13.99994569   0.        ]]



In [40]:
#test: make sure the evaluated policy is what we expected
expected_v = np.array([0, -14, -20, -22, -14, -18, -20, -20, -20, -20, -18, -14, -22, -20, -14, 0])
np.testing.assert_array_almost_equal(v, expected_v, decimal=2)

In [39]:
# Test: Make sure the evaluated policy is what we expected
expected_v = np.array([0, -14, -20, -22, -14, -18, -20, -20, -20, -20, -18, -14, -22, -20, -14, 0])
np.testing.assert_array_almost_equal(v, expected_v, decimal=2)